version: "3.8"
services:
  backend:
    build:
      context: ./backend\ v2
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend\ v2/.env
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend\ v2
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - backend
